### PR TITLE
Allow php 8.3 and update deps

### PR DESCRIPTION
**Pull request by fezfez**
- phpunit ^10
- doctrine/coding-standard ^12

### CODE REVIEW

**Comment by fezfez** [comment]
see https://github.com/laminas/laminas-continuous-integration-action/issues/130

**Comment by fezfez** [comment]
https://github.com/maglnet/ComposerRequireChecker not ready yet for php 8.3

**Comment by fezfez** [comment]
@Ocramius -caused by `No code coverage driver available ` and everything is update, do you know why this happen ?-

EDIT :  ah never mind, its https://github.com/laminas/laminas-continuous-integration-action/issues/130

**Comment by fezfez** [comment]
ping @Ocramius :1st_place_medal:

**Review by Ocramius — APPROVED** [review]
Thanks @fezfez!

**Pull request merged**
